/** Render only the review copy as a user would see the PNG. The original
 * generated bytes (including alpha) remain the asset returned to the child.
 * RGB underneath fully transparent pixels is not visible artwork. */
export const CHARACTER_REVIEW_MATTE = 236;
const MAX_REVIEW_PIXELS = 4_194_304;
const PNG_SIGNATURE = [137, 80, 78, 71, 13, 10, 26, 10];

function read32(bytes: Uint8Array, offset: number) {
  return new DataView(
    bytes.buffer,
    bytes.byteOffset,
    bytes.byteLength,
  ).getUint32(offset);
}

function paeth(left: number, above: number, corner: number) {
  const estimate = left + above - corner;
  const a = Math.abs(estimate - left),
    b = Math.abs(estimate - above),
    c = Math.abs(estimate - corner);
  return a <= b && a <= c ? left : b <= c ? above : corner;
}

async function inflateBounded(bytes: Uint8Array, expected: number) {
  const reader = new Blob([Uint8Array.from(bytes)])
    .stream()
    .pipeThrough(new DecompressionStream('deflate'))
    .getReader();
  const output = new Uint8Array(expected);
  let offset = 0;
  try {
    for (;;) {
      const { value, done } = await reader.read();
      if (done) break;
      if (offset + value.length > expected)
        throw new Error('Unexpected PNG decoded size');
      output.set(value, offset);
      offset += value.length;
    }
    if (offset !== expected) throw new Error('Truncated PNG pixels');
    return output;
  } finally {
    await reader.cancel().catch(() => {});
    reader.releaseLock();
  }
}

const crcTable = Uint32Array.from({ length: 256 }, (_, value) => {
  let crc = value;
  for (let bit = 0; bit < 8; bit++)
    crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
  return crc >>> 0;
});

function pngChunk(type: string, data: Uint8Array) {
  const result = new Uint8Array(data.length + 12);
  const view = new DataView(result.buffer);
  view.setUint32(0, data.length);
  result.set(new TextEncoder().encode(type), 4);
  result.set(data, 8);
  let crc = 0xffffffff;
  for (let index = 4; index < result.length - 4; index++)
    crc = (crc >>> 8) ^ crcTable[(crc ^ result[index]) & 255];
  view.setUint32(result.length - 4, (crc ^ 0xffffffff) >>> 0);
  return result;
}

export async function compositeCharacterReviewPng(
  bytes: Uint8Array,
): Promise<Uint8Array> {
  if (
    bytes.length < 45 ||
    PNG_SIGNATURE.some((value, index) => bytes[index] !== value) ||
    read32(bytes, 8) !== 13 ||
    new TextDecoder().decode(bytes.subarray(12, 16)) !== 'IHDR'
  )
    throw new Error('Invalid review PNG');
  const width = read32(bytes, 16),
    height = read32(bytes, 20);
  if (
    !width ||
    !height ||
    width > 4096 ||
    height > 4096 ||
    width * height > MAX_REVIEW_PIXELS ||
    bytes[24] !== 8 ||
    ![4, 6].includes(bytes[25]) ||
    bytes[26] !== 0 ||
    bytes[27] !== 0 ||
    bytes[28] !== 0
  )
    throw new Error('Unsupported review PNG');
  const channels = bytes[25] === 6 ? 4 : 2;
  const chunks: Uint8Array[] = [];
  let total = 0,
    offset = 8,
    ended = false;
  while (offset + 12 <= bytes.length) {
    const length = read32(bytes, offset);
    if (length > bytes.length - offset - 12)
      throw new Error('Truncated PNG chunk');
    const type = new TextDecoder().decode(
      bytes.subarray(offset + 4, offset + 8),
    );
    if (type === 'IDAT') {
      chunks.push(bytes.subarray(offset + 8, offset + 8 + length));
      total += length;
    }
    offset += length + 12;
    if (type === 'IEND') {
      ended = true;
      break;
    }
  }
  if (!ended || !total) throw new Error('Incomplete review PNG');
  const compressed = new Uint8Array(total);
  offset = 0;
  for (const chunk of chunks) {
    compressed.set(chunk, offset);
    offset += chunk.length;
  }
  const rowBytes = width * channels;
  const inflated = await inflateBounded(compressed, (rowBytes + 1) * height);
  const rgbRows = new Uint8Array((width * 3 + 1) * height);
  let previous = new Uint8Array(rowBytes),
    current = new Uint8Array(rowBytes);
  offset = 0;
  for (let y = 0; y < height; y++) {
    const filter = inflated[offset++];
    if (filter > 4) throw new Error('Invalid PNG filter');
    for (let x = 0; x < rowBytes; x++) {
      const left = x >= channels ? current[x - channels] : 0;
      const above = previous[x];
      const corner = x >= channels ? previous[x - channels] : 0;
      const predictor =
        filter === 1
          ? left
          : filter === 2
            ? above
            : filter === 3
              ? Math.floor((left + above) / 2)
              : filter === 4
                ? paeth(left, above, corner)
                : 0;
      current[x] = (inflated[offset++] + predictor) & 255;
    }
    for (let x = 0; x < width; x++) {
      const pixel = x * channels,
        alpha = current[pixel + channels - 1];
      const destination = y * (width * 3 + 1) + 1 + x * 3;
      for (let color = 0; color < 3; color++)
        rgbRows[destination + color] = Math.round(
          (current[pixel + (channels === 2 ? 0 : color)] * alpha +
            CHARACTER_REVIEW_MATTE * (255 - alpha)) /
            255,
        );
    }
    [previous, current] = [current, previous];
  }
  const encoded = new Uint8Array(
    await new Response(
      new Blob([rgbRows])
        .stream()
        .pipeThrough(new CompressionStream('deflate')),
    ).arrayBuffer(),
  );
  const header = new Uint8Array(13);
  new DataView(header.buffer).setUint32(0, width);
  new DataView(header.buffer).setUint32(4, height);
  header[8] = 8;
  header[9] = 2; // RGB, deliberately opaque review-only matte.
  const parts = [
    new Uint8Array(PNG_SIGNATURE),
    pngChunk('IHDR', header),
    pngChunk('IDAT', encoded),
    pngChunk('IEND', new Uint8Array()),
  ];
  const result = new Uint8Array(
    parts.reduce((sum, part) => sum + part.length, 0),
  );
  offset = 0;
  for (const part of parts) {
    result.set(part, offset);
    offset += part.length;
  }
  return result;
}
